server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csoits?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
